name: wonder_words
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.4.0
  freezed_annotation: ^2.4.1
  floor: ^1.5.0
  infinite_scroll_pagination: ^4.0.0
  logger: ^2.3.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  dio: ^5.4.3+1
  fluttertoast: ^8.2.6
  validators: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  redacted: ^1.0.11
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  floor_generator: ^1.5.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.11

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo_flutter.png
    - assets/images/splash.png

  fonts:
    - family: font1
      fonts:
        - asset: assets/fonts/font1_bold.ttf

